### ISSUE TITLE
1.0.18 build out of source is broken.

### ISSUE THREAD

**Issue by senior7515** [sctp/lksctp-tools#30]
To reproduce: 

1. checkout the 1.0.18 source
2. run ./bootstrap in the source
3. mkdir build &&  <SOURCE_DIR>/configure --prefix=<foo> --srcdir=<SOURCE_DIR> 

Result  is 

```
lksctp-tools/src/lib/sendmsg.c:27:10: fatal error: netinet/sctp.h: No such file or directory
 #include <netinet/sctp.h>
```
Note that this works on 1.0.17
